---
distribution_type: container
container_release_tag: 1.0.1
container_pull_registry: nexus3.acumos.org:10004
container_push_registry: nexus3.acumos.org:10002
project: model-deployments/deployment-client
ref: 5de6596e5260c05238ad6cc54de87a95f6a563c1
containers:
    - name: deployment-client
      version: 1.0.1
