---
distribution_type: container
container_release_tag: 1.0.5
container_pull_registry: nexus3.acumos.org:10004
container_push_registry: nexus3.acumos.org:10002
project: model-deployments/deployment-client
ref: ec3e2da4e11eb7eda0e964e1f3821517c589abcc
containers:
    - name: deployment-client
      version: 1.0.5
